@echo off
echo Deploying Frontend to Netlify...
cd frontend
echo Installing dependencies...
npm install
echo Building for production...
npm run build
echo Deploying to Netlify...
netlify deploy --prod --dir=dist
echo Frontend deployment complete!
pause